[package]
name = "soy_stemmer"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "soy_stemmer"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.24.0"
rust-stemmers = "1.2.0"
hashbrown = "0.12.0"